<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Plattipus.LazyCollections</PackageId>
        <PackageVersion>0.0.1</PackageVersion>
        <Authors>Andrew Platt</Authors>
        <Description>A tiny library for at-most-once enumeration of .NET Enumerables</Description>
        <Copyright>Copyright © 2026 Andrew Platt</Copyright>
        <PackageProjectUrl>https://github.com/andrewtplatt/LazyCollections</PackageProjectUrl>
        <RepositoryUrl>https://github.com/andrewtplatt/LazyCollections</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>enumerable lazy collection</PackageTags>

        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

</Project>
